name: "bcl2fastq"
description: Demultiplex Illumina BCL files
keywords:
  - demultiplex
  - illumina
  - fastq
tools:
  - "bcl2fastq":
      description: "Demultiplex Illumina BCL files"
      homepage: "https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software"
      documentation: "https://support.illumina.com/content/dam/illumina-support/documents/documentation/software_documentation/bcl2fastq/bcl2fastq2-v2-20-software-guide-15051736-03.pdf"
      licence: "ILLUMINA"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', run:'220726_M0720', mismatch: '1', base_mask: '', no_lane_split: '', ignore_map: [:]]
        # no_lane_split can be null, ignore_map can be null. In ignore_map, ONLY "bcls", "filter", "positions", "controls" are allowed.
  - samplesheet:
      type: file
      description: "Input samplesheet"
      pattern: "*.{csv}"
  - run_dir:
      type: directory
      description: "Input run directory containing RunInfo.xml and BCL data"
  - casava_dir: # Need to create it before running demultiplex. Can be relative or absolute path
      type: directory
      description: "Output directory where fastq files will be stored"

output:
  - control_fastq:
      type: file
      description: Demultiplexed control sample FASTQ files if available
  - fastq:
      type: file
      description: Demultiplexed sample FASTQ files
      pattern: "**_S*_L00?_R?_00?.fastq.gz"
  - undetermined:
      type: file
      description: Optional undetermined sample FASTQ files
      pattern: "Undetermined_S0_L00?_R?_00?.fastq.gz"
  - reports:
      type: file
      description: Demultiplexing Reports
      pattern: "Reports/*"
  - stats:
      type: file
      description: Statistics files
      pattern: "Stats/*"

authors:
  - "@huyu335"
